version: '3'
services:
  elasticsearch:
    image: elasticsearch:7.9.2
    environment:
      discovery.type: single-node
  logstash:
    image: logstash:7.9.2
    ports:
      - 127.0.0.1:5959:5959/udp
    volumes:
      - ./pipeline/:/usr/share/logstash/pipeline/
    depends_on:
      - elasticsearch
  kibana:
    image: kibana:7.9.2
    ports:
      - 127.0.0.1:5601:5601
    depends_on:
      - elasticsearch
  elasticsearch-hq:
    image: elastichq/elasticsearch-hq
    ports:
      - 127.0.0.1:5000:5000
    depends_on:
      - elasticsearch
