version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - 127.0.1.1:2181:2181
  kafka:
    image: wurstmeister/kafka
    ports:
      - 127.0.0.1:9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_CREATE_TOPICS: behaviorlog:1:1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
